name: Build Container Image

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git Repository
      uses: actions/checkout@v2.4.2
    - name: Log in to Github Packages
      uses: docker/login-action@v2.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: downcase REPO
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
    - name: Build and Push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ env.REPO }}:latest
